name: PROXY Updater

on: workflow_dispatch

jobs:
  health_check_job:
    runs-on: ubuntu-latest
    name: Check all sites
    steps:
      - uses: actions/checkout@v2
      - name: Run Shell Script
        id: shell_script_run
        run: bash ./update-data.sh
